// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChangeEquipOnBattleMZ","status":true,"description":"[Ver1.1.0]Add equipment change command to actor commands","parameters":{"commandName":"Equip"}},
{"name":"ChangeSelectItemWindowMZ","status":true,"description":"Change the various settings of item selecting window.","parameters":{"Switch ID":"1","Max Columns":"1","Visible Rows":"8","X position":"-1","Y position":"-1","Width":"-1"}},
{"name":"HPConsumeSkill","status":true,"description":"make the skill that consumes HP, not only MP and/or TP","parameters":{"Consume HP Color":"17"}},
{"name":"MenuSubMembersMZ","status":false,"description":"Display sub members at menu window and map as followers","parameters":{"subMemberIdVal1":"1","subMemberIdVal2":"2","subMemberIdVal3":"3","subMemberIdVal4":"4","subMemberText":"Sub Members","displayIfNone":"false","subMemberNoneText":"None","DisplayOnMap":"true","additionalFollower":"4"}},
{"name":"SVActorPositionMZ","status":true,"description":"Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"700","actor1 Ypos":"320","actor2 Xpos":"700 + 32","actor2 Ypos":"320 + 48","actor3 Xpos":"700 + 32 * 2","actor3 Ypos":"320 + 48 * 2","actor4 Xpos":"700 + 32 * 3","actor4 Ypos":"320 + 48 * 3"}},
{"name":"Yami_8DirEx","status":true,"description":"Player can 8-dir move, also touch input movement.","parameters":{"dir4 Switch ID":"100"}},
{"name":"WeatherOnBattle","status":true,"description":"display weather not only map but also battle","parameters":{}},
{"name":"SubMembersAttendBattle","status":false,"description":"[Ver1.0.1]Make Sub Members(=NPC) Attend Battle and does auto actions.","parameters":{"subMemberIdVal1":"1","subMemberIdVal2":"2","subMemberIdVal3":"3","subMemberIdVal4":"4"}},
{"name":"ShiftEnemies","status":true,"description":"Adjust the enemy placement according to your game resolution automatically.  Tweaked by Restart for MV","parameters":{}},
{"name":"NUUN_BattlerOverlayBase","status":true,"description":"バトラーオーバーレイベース","parameters":{"ConflictScale":"'Img'","CoordinateMode":"'Default'"}},
{"name":"NUUN_ButlerHPGauge","status":true,"description":"バトラーHPゲージ","parameters":{"EnemySetting":"------------------------------","EnemyVisibleSetting":"------------------------------","HPPosition":"0","HPVisible":"0","GaugeSetting":"------------------------------","GaugeWidth":"128","GaugeHeight":"12","Gauge_X":"0","Gauge_Y":"0","HPLabelVisible":"true","HPValueVisible":"true","ValueFontSize":"-6","LabelFontSize":"-2","MaskValueName":"????","SpecialSetting":"------------------------------","HPVisibleMode":"0","EnemyBookSetting":"------------------------------","HPEnemyBookVisible":"0","ActorSetting":"------------------------------","ActorVisibleSetting":"------------------------------","ActorHPPosition":"-1","ActorHPVisible":"0","ActorGaugeSetting":"------------------------------","ActorGaugeWidth":"128","ActorGaugeHeight":"12","ActorGauge_X":"0","ActorGauge_Y":"0","ActorHPLabelVisible":"true","ActorHPValueVisible":"true","ActorValueFontSize":"-6","ActorLabelFontSize":"-2"}},
{"name":"LL_SprashScreen","status":false,"description":"スプラッシュスクリーンを表示します。","parameters":{"splashImages":"[\"Waccland Entertainments presents\"]","skipEnabled":"true","debugDisabled":"true","jingleSettings":"","meName":"","meVolume":"90","mePitch":"100","mePan":"0"}}
];
